[project]
name = "HiveDisCured"
version = "1.0.0"
description = "A Discord bot for Hive blockchain tokenized curation governance projects."
authors = ["https://peakd.com/@yaziris"]
requires-python = ">=3.11,<3.12"
dependencies = [
    "beem==0.24.26",
    "discord-py==2.3.2",
]
